AppleWin/AppleWin

source/Disk.cpp
source/Memory.cpp
source/Tape.cpp

- Removed old disk stepping code as DataWiz confirmed he modified his Chessmaster 2000 crack to work on old AppleWin - this closes #133 (Berlios bug #18109) - see: https://groups.google.com/d/topic/comp.sys.apple2/xHrW45igYY8/discussion
- Changed Disk_IORead and Disk_IOWrite and related functions to better reflect actual Disk II controller operation, mainly around reading & writing the latch
- Added a floppyloadmode variable for emulating $C08D (see UTA2E page 9-13) but commented out use of it as it's mostly implicit in this implementation
- Tidied up logic in DiskReadWrite
- Improved disk debug logging
- Added TODO: ImageWriteTrack shouldn't take pFloppy->phase as a parameter

Removed old disk stepping code - this closes #133 (Berlios bug #18109)

---

source/Frame.cpp

Tweaks:
* Full-screen: Correctly erase the PAUSED or STEPPING text status
* 2x windowed mode: draw the the correct size 3d rect

Full-screen and 2x tweaks for Status Area

---

source/Applewin.cpp
source/Debugger/Debug.cpp
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Symbols.cpp
source/DiskImageHelper.cpp
source/Log.cpp
source/ParallelPrinter.cpp

applewin\source\applewin.cpp(761): warning C6385: Reading invalid data from '"Disk Image"':  the readable size is '11' bytes, but '21' bytes may be read.
applewin\source\debugger\debug.cpp(6624): warning C6386: Buffer overrun while writing to 'sName':  the writable size is '31' bytes, but '32' bytes might be written.
applewin\source\debugger\debugger_display.cpp(3715): warning C6053: The prior call to 'strncpy' might not zero-terminate string 'sText'.
applewin\source\log.cpp(42): warning C6053: The prior call to '_vsnprintf' might not zero-terminate string 'output'.
applewin\source\debugger\debug.cpp(2759): warning C6011: Dereferencing NULL pointer 'pFont'.
applewin\source\debugger\debugger_symbols.cpp(243): warning C6053: The prior call to '_tcsncpy' might not zero-terminate string …

Fix the following errors reported by VS2017 Code Analysis.

---

source/Applewin.cpp
source/Common.h
source/LanguageCard.cpp
source/LanguageCard.h
source/Memory.cpp
source/SaveState.cpp

PR for #590.
Apple II original defaults to no LC in slot-0.
Adds new cmd-line switches: `-s0 <languagecard|lc>` to enable LC in slot-0.
When LC is enabled, it replaces the Apple II's F8 ROM with the II+'s F8 auto-start ROM.

Apple II original: default to 48K (ie. no Language Card)

---

source/LanguageCard.cpp
source/LanguageCard.h
source/Memory.cpp
source/Memory.h
source/SaveState.cpp

. MemSetPaging() now not used for $C080-C08F accesses.
- Instead LC registers its own I/O handler like all other slot 1-7 cards.
. Saturn uses base LC's 16K for bank0
. Move all 'modechanging = 0' to UpdatePaging()

Refactor Language Card

---

resource/Applewin.rc
source/Applewin.cpp
source/Debugger/Debugger_Display.cpp
source/Frame.cpp
source/NTSC.cpp
source/NTSC_CharSet.cpp
source/NTSC_CharSet.h
source/Video.cpp
source/Video.h

PR for #574.
Adds new cmd-line switches: -videorom <filename> to replace the video ROM for the Enhanced //e.
ROM sizes of 4K, 8K and 16K (top 8K only) are supported.
NB. The rocker switch is set to European video ROM.
F10 (for //e or Enhanced //e models) emulates the PAL //e's rocker switch (under the keyboard) to toggle between European or US video ROM.
Other:
. Fixed debugger's view of the AltCharSet soft-switch (it was showing the opposite state).

Add support for PAL/bilingual or custom 8K video ROMs

---

.gitignore

Just a cache directory missing from `.gitignore`.

Ignore VS2017 database/IntelliSense folder

---

AppleWinExpress2017.vcxproj
bin/History.txt
docs/ToDo.txt
source/CommonVICE/interrupt.h
source/CommonVICE/mem.h
source/CommonVICE/types.h
source/Debugger/Debug.cpp
source/Keyboard.cpp
source/ParallelPrinter.cpp
source/z80emu.cpp
source/z80emu.h

Compilation fails on some of these files on computers with certain locales (e.g. CJK) otherwise.

Convert files with special characters to UTF-8

---

source/SaveState.cpp

The state load function resets the machine too aggressively in my opinion. Occasionally I press F12 instead of F11 to save a state, and after specifying an invalid file name get an error and the system resets, despite no configuration being set. For those minor errors that occur at the start of the state load process, instead of throwing an exception, this displays the error message and cancels the state load.

Do not reset on minor state load errors

---

source/Applewin.cpp
source/Applewin.h
source/Configuration/About.cpp
source/Configuration/PageConfig.cpp
source/Configuration/PageConfigTfe.cpp
source/Configuration/PageDisk.cpp
source/Configuration/PropertySheetHelper.cpp
source/Disk.cpp
source/Frame.cpp
source/Harddisk.cpp
source/Registry.cpp
source/Registry.h
source/StdAfx.h
source/Video.cpp

This change does two things:
**1. Updates the registry APIs to reduce the likelihood of uninitialized
variables.**
The code wasn't always checking the return value of registry load operations.
In some cases, this led to uninitialized memory being used, and crashes could
result. For example, LoadConfiguration in Applewin.cpp was using an
uninitialized value for the computer type if no registry variable for the
"Apple 2 type" was set.
New registry reading methods and macros have also been introduced, allowing
default value fallbacks for the cases where a registry variable is not found.
This makes registry access simpler and safer when a default value is known in
advance.
The registry code's style has also been updated to conform with the rest of
the code base (tabs instead of spaces, naming …

Prevent uninitialized value bugs and improve string safety.

---

source/Debugger/Debugger_Symbols.cpp

Unchecked null result of strstr() may cause random crashes. Well, strstr() returns null (at least so it seems) for all empty lines in the *.SYM files, but not crashing all the times somehow.

Fix random crash upon start up.

---

source/DiskImage.cpp
source/DiskImageHelper.cpp
source/DiskImageHelper.h

ImageInfo must be initialised by calling its c++ constructor (as it contains std::string).
In VS it seems to work (by chance?), in g++ it fails.
C++ standard requires the constructor anyway.

Memory fix

---

help/CommandLine.html
source/Applewin.cpp
source/Registry.cpp

This change adds the `-conf` switch which, if specified, will use an INI-file instead of the Windows Registry.
This affects AppleWin/AppleWin#709 and AppleWin/AppleWin#446.
I tested this using VS2019 on Windows 10.
1. Open PowerShell and navigate to the folder containing `AppleWin.exe`.
2. Run `AppleWin.exe -conf config.ini`, where `config.ini` is a non-existing file.
3. Close AppleWin.
4. Note the creation of `config.ini`. Also note that no values in the Registry should be changed (this is easy to test if you remove the AppleWin group first so you can see that nothing is created).
5. Run `AppleWin.exe` normally (without `-conf`). Change some settings. Notice that the Registry is used and the `config.ini` is unaffected.

Allow use of an INI-file instead of the Registry

---

source/NTSC.cpp

PR for #763.
Attention paid to "NTSC Monitor" mode when MIXED (lines 160-191 are TEXT) or demos that switch video modes mid-scanline.
Tested with:
- https://github.com/AppleWin/AppleWin-Test/blob/master/v2/Tests-Various.dsk
- FT's ANSI STORY & TRIBU demos

Support for PAL killing color-burst during TEXT video mode

---

source/Applewin.cpp
source/NTSC.cpp
source/NTSC.h
source/RGBMonitor.cpp
source/RGBMonitor.h

Added support for extra RGB modes of some video cards. (#819)
Currently only Apple RGB and Video7 SL7 are supported.
The RGB videocard can be defined through command-line:
`-rgb-card-type: apple (default), sl7, eve, feline`
The default text color can be modified when SL7 is selected. On the actual card this was defined by dip switches.
`-rgb-card-foreground <color>`
<color> can be 6 (blue), 9 (amber), 12 (green) and white (15)
Video7 SL7 extra modes (from the manual), modes 7 to 11. The others are the usual Apple RGB modes:
Note that mode 11 is actually incompatible with Apple RGB and other cards, which renders it as a B&W Hires.
In `NTSC` and `RGBMonitor`, some new functions were defined to handle RGB text and duochrome (F/B) 7-pixels cells. When the RGB monitor is selected, the text …

Video7 SL7 RGB extra modes

---

source/Applewin.cpp
source/Configuration/PageConfig.cpp
source/NTSC.cpp
source/RGBMonitor.cpp
source/RGBMonitor.h
source/Video.cpp
source/Video.h

This is a revised version of PR #832.
New features since #832:
- New video mode, as proposed in #832
- Legacy RGB rendering is back
- On-the-fly RGB palette switch for some cards
- HIRES RGB rendering
- This is a new branch with only the most recent commits
Previous PR features:
- Fixed the SL7 color text features
- Support for Le Chat Mauve Féline/IIc adapter (under Video7 patent)
- DHIRES color & mixed mode rewrite
- DHIRES modes setup cleanup _(needs review)_
Details:
- New video mode, as proposed in #832
The available video modes are now:
```
const char *g_apVideoModeDesc[ NUM_VIDEO_MODES ] =
{
"Monochrome (Custom)"
, "Color (RGB Idealized)"
, "Color (RGB Card/Monitor)"
, "Color (Composite Monitor)"
, "Color TV"
, "B&W TV"
, "Monochrome (Amber)"
, "Monochrome (Green)"
, "Monochrome …
```

RGB Videocards

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.cpp
source/Debugger/Debugger_Console.cpp
source/Debugger/Debugger_DisassemblerData.cpp
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Display.h
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Parser.cpp

Minor clean-up changes in the Debugger code to fix some compiler warnings. Mainly affects forgotten, unused local variables.

Debugger, minor clean-up: compiler warnings, unused variables etc

---

AppleWinExpress2008.vcproj
AppleWinExpress2019.vcxproj
AppleWinExpress2019.vcxproj.filters
source/Applewin.cpp
source/Applewin.h
source/CPU.cpp
source/CPU.h
source/CPU/cpu6502.h
source/CPU/cpu65C02.h
source/Common.h
source/Frame.cpp
source/Mockingboard.cpp
source/Mockingboard.h
source/MouseInterface.cpp
source/MouseInterface.h
source/NTSC.cpp
source/NTSC.h
source/SaveState.cpp
source/SynchronousEventManager.cpp
source/SynchronousEventManager.h
source/Video.cpp
test/TestCPU6502/TestCPU6502-vs2008.vcproj
test/TestCPU6502/TestCPU6502-vs2019.vcxproj
test/TestCPU6502/TestCPU6502-vs2019.vcxproj.filters
test/TestCPU6502/TestCPU6502.cpp

PR for #612.
Switched Mockingboard/6522 Timer interrupts & Mousecard's VBlank interrupt to use synchronous events.
This is a linked-list of ordered timer-based event, where _only the head_ of the list needs updating after every opcode.
Improvements:
- 6502 interrupts are now cycle accurate in full-speed (unthrottled) mode (eg. fixes Broadsides, #608)
- Also FT demos (eg. MAD2) can be toggled full-speed on/of without losing the video/6522 sync.
- The emulation performance is now unaffected by having Mockingboard 6522 timers, as it's not having to update the 4x 6522 timers after every opcode!
Tested with _all_ FT demos (eg. "CHIP" uses 6522-A & 6522-B timer1 interrupts during the video frame, "TRIBU" re-uses the 6522-A timer1 interrupt as it scans down the video frame). Also tested with …

Support for synchronous events

---

source/CPU.cpp
source/CardManager.cpp
source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.cpp
source/Debugger/Debugger_Assembler.h
source/Debugger/Debugger_Color.cpp
source/Debugger/Debugger_DisassemblerData.cpp
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Symbols.cpp
source/Debugger/Debugger_Types.h
source/Disk2CardManager.cpp
source/Memory.cpp
source/MouseInterface.cpp
source/ParallelPrinter.cpp
source/SaveState_Structs_v1.h
source/Speaker.cpp
source/Speaker.h
source/YamlHelper.h

Another set of commits fixing compiler warnings and portability issues.
While the changes may not be required for MSVC (some will depend on the compiler warning lelvel) , they should not hurt - and even provide some clean-up.
It's mainly issues reported by gcc, such as some naming conflicts of local variables with gcc standard library symbols. It would really help/ease the synchronization of sources with the Linux port, if you could take these minor changes upstream. 
The final two commits fix two general issues:
* confusing behavior when entering the builtin (mini) assembler mode,
* and also fixes the "cl" (clear flag) command - which was documented, but did not work at all (due to an "interesting" command/syntax conflict...).

Source clean-up, portability and debugger fixes.

---

help/CommandLine.html
source/Applewin.cpp
source/CardManager.h
source/Common.h
source/Configuration/PageAdvanced.cpp
source/Configuration/PageDisk.cpp
source/Configuration/PropertySheet.cpp
source/Configuration/PropertySheetHelper.cpp
source/Configuration/PropertySheetHelper.h
source/Disk.cpp
source/Disk.h
source/Disk2CardManager.cpp
source/Disk2CardManager.h
source/Harddisk.cpp
source/Harddisk.h
source/SaveState.cpp
source/SaveState.h

PR for #691.
Be smarter about both the path & filename when saving/loading a state-state file:
On save:
- Filename = (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
- if still empty, then use last save-state name
- if still empty, then leave it empty
- Path = (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
- if still empty, then use last save-state path
- if still empty, then use `g_sCurrentDir`
On load:
- Filename = last save-state name
- if empty then (in priority order) try: S7D1-HDD or S7D2-HDD or S6D1-floppy or S6D2-floppy or S5D1-floppy...
- if still empty, then leave it empty
- Path = last save-state path
- if still empty, then use `g_sCurrentDir`

Improve determining path & filename when saving/loading a save-state

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Display.cpp
source/Frame.cpp
source/Frame.h
source/Harddisk.cpp
source/Keyboard.cpp
source/Memory.h
source/Mockingboard.cpp
source/MouseInterface.cpp
source/SAM.cpp
source/SaveState.cpp
source/Speaker.cpp
source/SynchronousEventManager.cpp

Again, another set of minor fixes for compiler warnings etc, making AppleWin more portable.
Most changes are no-brainers, separated into individual commits for clarity.
The only functional change is another debugger fix for the data window. When entering the debugger and switching to the data window ("data" command in the console) then the cursor keys did not work. They only worked, once the mini dump #1 in the right panel was also activated ("md1" command) - which made no sense. When the data is visible in the main window, then the cursor keys should also work.
Commit comment concerning g_uMaxExPages/g_uActiveBank below is not quite accurate: they are still used, of course, but declared "static" and now local within Memory.cpp, which contradicts their "extern" declaration in the header …

More clean-up, portability and another debugger fix

---

source/Core.cpp
source/Memory.h
source/NTSC.h
source/Utilities.cpp
source/Video.cpp

Added a couple of .h as enums cannot be fwd declared.
Just include IPropertySheet.h and not concrete classes.
Make g_apVideoModeDesc static as it is not used elsewhere.
Remove space at end of definition of VERSIONSTRING_SIZE.

Some small changes to ensure code compiles with gcc.

---

source/NTSC.cpp
source/RGBMonitor.cpp
source/Video.h

In Windows it does not seem to make any difference, so 0xFF is selected for maximum compatibility.
Alternatively, I could add an #ifdef _MSC_VER, but then I am not clear why NTSC.cpp and RGBMonitor.cpp set the alpha to different values (0xFF and 0x00 respectively).
See: https://github.com/AppleWin/AppleWin/blob/master/source/NTSC.cpp#L176 and related usage.
Ideally all the 3 #define should go to a common .h (Video.h?) to avoid they diverge.
Will improve the patch if I get feedback on the above.

Select a Alpha value that works in Windows and Linux (qt / sdl).

---

source/Utilities.cpp
source/Utilities.h
source/Windows/WinFrame.cpp

Move GetAppleWindowTitle() to Utilities.cpp as it is generic.

---

source/Windows/WinFrame.cpp

1. Newer VC runtime stat(), when using 32-bit file size, returns error if file size is >2G. For file existence check, using 64-bit file size is more accurate as files bigger than 2G would be reported as non-existing otherwise.
2. <sys/stat.h> is required for VS2013 or before. Keeping backward compatibility is nice.

Use _stat64() to support file size >2G

---

source/CommonVICE/types.h
source/Configuration/PageConfigTfe.h
source/Tfe/Uilib.h
source/Z80VICE/daa.cpp
source/Z80VICE/z80.cpp
source/Z80VICE/z80mem.cpp

Some small commits to ease compilation with gcc.
Most of it is around duplicate definitions or #include of types from ``windows.h``.
In Linux a windows.h compatibility layer is required and it becomes harder if different files redefine some of it independently.

Cleanup types and #include to ease gcc compilation.

---

AppleWinExpress2008.vcproj
AppleWinExpress2019.vcxproj
AppleWinExpress2019.vcxproj.filters
source/CmdLine.cpp
source/Disk.cpp
source/Frame.h
source/Harddisk.cpp
source/Harddisk.h
source/Interface.h
source/Memory.cpp
source/MouseInterface.cpp
source/NTSC_CharSet.cpp
source/Pravets.cpp
source/SaveState.cpp
source/SoundCore.cpp
source/Speaker.cpp
source/Utilities.cpp
source/Video.cpp
source/Windows/WinFrame.h

This is not complete as header files from Windows/.. are still included in:
Keyboard.cpp
SerialComms.cpp
Joystick.cpp
But probably these are arch specific and will have to be completely reimplemented elsewhere.

Move Windows related function to Interface.h

---

source/Configuration/PropertySheetHelper.cpp
source/Debugger/Debug.cpp
source/Debugger/Debugger_Console.cpp
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Util_MemoryTextFile.cpp
source/Disk.cpp
source/DiskImage.cpp
source/DiskImage.h
source/DiskImageHelper.cpp
source/DiskImageHelper.h
source/Harddisk.cpp
source/LanguageCard.cpp
source/Memory.cpp
source/RGBMonitor.cpp
source/SerialComms.cpp
source/SoundCore.cpp
source/Windows/AppleWin.cpp
source/Windows/DirectInput.cpp
source/Windows/WinFrame.cpp
source/Windows/WinVideo.cpp
test/TestCPU6502/TestCPU6502.cpp

Replaced by malloc, free & memset.
The only tricky bit has been the fact that MEM_COMMIT implies zero-initialisation (which I had completely forgotten).
This was apparently only ever required in TestCPU6502.cpp (replaced by calloc), while other parts of the code were ignoring this feature and calling ZeroMemory just after a MEM_COMMIT.

Remove VirtualAlloc & Co.

---

source/Interface.h
source/NTSC.h
source/SoundCore.cpp

And ensure logic around DirectSoundEnumerate() cleans up devices discovered previously.

Small changes to improve compatibility with gcc.

---

source/FrameBase.cpp
source/FrameBase.h
source/Video.cpp
source/Video.h
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.h
source/Windows/WinFrame.cpp
source/Windows/WinVideo.cpp
source/Windows/WinVideo.h

Move generic functions to the base class as they can be reused by other archs.
Split VideoRefreshScreen() to extract the system-specific code to VideoPresentScreen().

WinVideo: share some generic code

---

source/Configuration/PageConfig.cpp
source/Configuration/PageDisk.cpp
source/Configuration/PropertySheetHelper.cpp
source/Debugger/Debug.cpp
source/Debugger/Debugger_Display.cpp
source/Disk.cpp
source/FrameBase.h
source/Harddisk.cpp
source/Keyboard.cpp
source/Pravets.cpp
source/Utilities.cpp
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h
source/Windows/WinFrame.cpp
source/Windows/WinFrame.h

This PR contains a few things (happy to split if necessary and to improve on feedback)
- simplify the interface FrameBase to make it easier to implement it for different cases (remove HDC and make parameters more explicit)
- remove functions which are only called on a Win32Frame (in which case a cast is guaranteed to succeed)
- otherwise there is the risk that every FrameBase implementation wants to add its own variants.
- video.VideoReinitialize(false); when changing the MonoChrome color: should the video address be reinitialised? I looked at the calls made for other video changes (F9, Shift-F9...) and for consistency changed it. But it might a mistake of mine.

FrameBase: some changes to ease implementations

---

source/Configuration/PageConfig.cpp
source/NTSC.cpp
source/SaveState.cpp
source/Video.cpp
source/Video.h
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h
source/Windows/WinFrame.cpp

This was originally discussed in https://github.com/AppleWin/AppleWin/pull/910#issuecomment-757303832
When VideoMode changes, call ``VideoReinitialize(false)``.
I still have one open question.
If this code is needed after a ``F9``: https://github.com/AppleWin/AppleWin/blob/master/source/Windows/WinFrame.cpp#L1254-L1258
should it be needed here as well:
https://github.com/AppleWin/AppleWin/blob/master/source/Windows/Win32Frame.cpp#L296
and here
https://github.com/AppleWin/AppleWin/blob/master/source/Configuration/PageConfig.cpp#L318
?
I might be trying too hard to make uniform parts of the code which are not meant to, they just look very similar.

Videoreinitialize: make code more uniform

---

AppleWinExpress2008.vcproj
AppleWinExpress2019.vcxproj
AppleWinExpress2019.vcxproj.filters
source/Debugger/Debug.cpp
source/Debugger/Debugger_Display.cpp
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h
source/Windows/WinFrame.cpp
source/Windows/WinFrame.h

After this
- ``Win32Frame.cpp`` and ``WinFrame.cpp`` should be merged back
- Rename class ``Win32Frame`` -> ``WinFrame``?
- If there is a fear that ``Win32Frame::GetWin32Frame`` is expensive (``dynamic_cast``), I can remove it. (safely)

Move last remaining globals from WinFrame.cpp to Win32Frame.

---

source/Configuration/PageSound.cpp
source/Speaker.cpp
source/Speaker.h

The check (soundtype != newtype) is always false.
So we can remove dependency on a HWND argument.

SpkrSetEmulationType: simplify logic and remove unreachable code.

---

AppleWinExpress2019.vcxproj
source/Configuration/PropertySheetHelper.cpp
source/Configuration/PropertySheetHelper.h
source/Debugger/Debug.cpp
source/Debugger/Debug.h
source/Debugger/Debugger_Assembler.h
source/Debugger/Debugger_DisassemblerData.cpp
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Symbols.cpp
source/Debugger/Debugger_Types.h
source/SoundCore.cpp

This reduces the chances of incompatibility between gcc and vs.
99% is "const char *" literals.
1 case of a goto jumping over a variable declaration.

Enable ConformanceMode in VS2019.

---

source/Mockingboard.cpp

Moreover, it needs a constructor for correct initialisation.

Avoid leaks when the destructor of SY6522_AY8910 is not called.

---

source/Debugger/Debugger_Disassembler.cpp

The higher g_nDisasmCurLine the more we will have to travel back to find the instruction at the top of the window.
In AppleWin it does not matter because the line is halfway and so the result is the same.

Debugger: fix bound on maximum bytes to move backward.

---

source/Mockingboard.cpp
source/SSI263.cpp
source/SoundCore.cpp
source/SoundCore.h
source/Speaker.cpp

Need to use FAILED() instead of boolean check.
This is an update to the original PR https://github.com/AppleWin/AppleWin/pull/931/commits/ac214879e3581f93fbfa3fe85127f415068c806b

Fix to sound not working in modern environments.

---

source/Configuration/Config.h
source/Configuration/PageConfig.cpp
source/Configuration/PageConfigTfe.cpp
source/Configuration/PageConfigTfe.h
source/Configuration/PropertySheetHelper.cpp
source/Tfe/tfe.cpp
source/Tfe/tfe.h
source/Tfe/tfearch.cpp
source/Tfe/tfearch.h
source/Utilities.cpp

The Uthernet card had 2 non standard behaviours:
1. It would not be reapplied after a restart (missing call to `tfe_reset`)
2. Its settings would not behave like everything else: needed a full restart and could not be undone (hardware changes)
This patch fixes the above issues and makes the Uthernet card behave like any other hardware-changing setting.
The logic is that when reading the settings, the enabled and the iface name are simply stored, and when `tfe_init` is called in https://github.com/AppleWin/AppleWin/blob/27fe4e5ed0e9ab6637bd58b4f55a110786ccace5/source/Windows/AppleWin.cpp#L945 the card is first removed and then recreated taking into account all (new) settings

Uthernet: fix usability and settings

---

source/Configuration/PageDisk.cpp
source/Disk.cpp
source/Harddisk.cpp

This was already happening for Hard Disks (although in a convoluted way).
Extend to Floppy Disks.

Disks: save full pathname to registry.

---

source/Card.h
source/CardManager.cpp
source/CardManager.h
source/Common.h
source/Configuration/Config.h
source/Configuration/IPropertySheet.h
source/Configuration/PageConfig.cpp
source/Configuration/PageDisk.cpp
source/Configuration/PropertySheet.h
source/Configuration/PropertySheetHelper.cpp
source/Configuration/PropertySheetHelper.h
source/Disk.cpp
source/Harddisk.cpp
source/Harddisk.h
source/Registry.cpp
source/Registry.h
source/SaveState.cpp
source/SerialComms.cpp
source/SerialComms.h
source/Utilities.cpp
source/Windows/AppleWin.cpp

Encompasses PR #956.
Initially all cards are removed before loading save-state.
Use new Registry "Configuration/Slot 2" location to save SSC's port name.
Use new Registry "Configuration/Slot 7" location to save HDV's image names.
Use new Registry "Configuration/Slot n" (and "Configuration/Slot Auxiliary") locations to save all other card types.
Command line: -s\<slot\> <card> (eg. -s7 empty) now get persisted to the Registry.
Only update 'HDV Starting Directory' for slot7 & drive1.

Improve save-state card mgmt

---

source/Configuration/Config.h
source/Configuration/PropertySheetHelper.cpp
source/SaveState.cpp

1. separate class initialisation from loading settings (to avoid static variable initialisation loop)
2. include all slots (so to match the usage in SaveState.cpp)
3. in SaveState simply create an object before and after loading the yaml file, and compare them
4. remove RestoreCurrentConfig as it does not actually do anything (AW state is not touched so it does not need to be reset)

Simplify logic around CConfigNeedingRestart

---

AppleWinExpress2008.vcproj
AppleWinExpress2019.vcxproj
AppleWinExpress2019.vcxproj.filters
source/Card.cpp
source/Card.h
source/CardManager.cpp
source/CardManager.h
source/Disk.h
source/FourPlay.h
source/Harddisk.cpp
source/Harddisk.h
source/LanguageCard.cpp
source/LanguageCard.h
source/Memory.cpp
source/MouseInterface.h
source/SAM.h
source/SNESMAX.h

Add `Card::InitializeIO`: so one can remove all the inlined checks for card type.
Other areas of improvement:
- `Card::Reset()` probably exactly the same could be done: see https://github.com/AppleWin/AppleWin/blob/ff7c9dc185aed1352e570c583c206af900a8e4f8/source/Utilities.cpp#L541-L559
- `Card::Update(executedCycles)`: https://github.com/AppleWin/AppleWin/blob/ff7c9dc185aed1352e570c583c206af900a8e4f8/source/Windows/AppleWin.cpp#L220-L223
- `Card::Destroy()`?

Card::InitializeIO

---

source/Card.cpp
source/Card.h
source/CardManager.cpp
source/CardManager.h
source/Disk.cpp
source/Disk.h
source/Disk2CardManager.cpp
source/Disk2CardManager.h
source/FourPlay.h
source/Harddisk.h
source/LanguageCard.h
source/MouseInterface.h
source/SAM.h
source/SNESMAX.h
source/SerialComms.h
source/Utilities.cpp
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.cpp

Add a method to allow cards to execute their update code.
A couple of points:
- `GetCardMgr().GetDisk2CardMgr().Update(executedcycles);` is only used in the benchmark code. Should it become `CardManager::Update()`?
https://github.com/AppleWin/AppleWin/blob/8662a9917964d0ee1005829153ff0bbb082b813f/source/Windows/Win32Frame.cpp#L299
- This line https://github.com/AppleWin/AppleWin/blob/8662a9917964d0ee1005829153ff0bbb082b813f/source/Windows/Win32Frame.cpp#L300 passes ``cycles`` rather then ``nExecutionPeriodUsec``, is it ok?
- Looking at the rest of the code e.g. https://github.com/AppleWin/AppleWin/blob/8662a9917964d0ee1005829153ff0bbb082b813f/source/Utilities.cpp#L539 I wonder if there should be a small set of well defined operations that all card should implement
1. Boot
2. Init
3. …

Card::Update()

---

source/Joystick.cpp
source/Joystick.h
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.cpp

Over time `JoyUpdateButtonLatch()` has morphed away from the original AppleWin 1.00 code, where `JoyUpdateButtonLatch()` was called once every 2048 emulated cycles, and each `buttonlatch` was decremented by 1 each update. NB. 2048 x BUTTONTIME(5000) = 10M cycles = 10 seconds.
The logic in `CheckJoystick0()` was (and still is) like this:
- if button-0 is pressed:
- if button-0 wasn't pressed last time, then `buttonlatch[0] = BUTTONTIME` (ie. 5000)
- `joybutton[0] = TRUE`
- if button-0 not pressed:
- `joybutton[0] = FALSE`
Then later when the Apple II reads $C061 (BUTTON0 I/O port):
- `pressed = buttonlatch[0] || joybutton[0]`
- `buttonlatch[0] = 0`
- `return pressed<<7`
So the original code would latch the button-0 press for up to 10 seconds!
NB. This was for joystick buttons, not for …

Remove Joystick's buttonlatch & BUTTONTIME

---

source/CardManager.cpp
source/CardManager.h
source/Debugger/Debugger_Display.cpp
source/LanguageCard.cpp
source/LanguageCard.h
source/Memory.cpp
source/Memory.h
source/SaveState.cpp
source/Windows/AppleWin.cpp

While I was working on the other PRs re Card interface, I realised that the `Slot0` card information is stored in separate locations
1. the `Slot0` type (but the card is always a `DummyCard`)
2. the `g_pLanguageCard` global variable (which contains the instance)
This change moves all the information to the slot 0 of the `CardManager` and I think simplifies the logic.
There is an important point not to forget, is that for a //e the Slot 0 MUST ALWAYS contains a `LanguageCardUnit` (of type `CT_LanguageCardIIe`). And I have added an `ASSERT` about this, so it cannot be missed.
This is not new, it used to be done in https://github.com/AppleWin/AppleWin/blob/443545b0f6d31349eb365956ab948561e889cc15/source/Memory.cpp#L352

Slot0: make it more uniform to other slots.

---

source/FrameBase.cpp
source/FrameBase.h
source/Video.cpp
source/Video.h
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h

1. Header was not packed properly
2. static assert did not work on gcc / clang
3. added `FrameBase::Video_GetScreenShotFolder` to let frontends customise where to save the screenshots
4. added the size to the bitmap header: to make it more compliant

Correct Bmp creation on Linux

---

source/Video.cpp

https://github.com/audetto/AppleWin/issues/57

Screenshot: reset file pointer to the end.

---

source/ParallelPrinter.cpp

Only send writes to address $C090 (although the code is generalized in case the PCI is inserted into a different slot) to the printer. PrintShop was also writing to the strobe ($C092) which should not be interpreted as a data byte.
Tested with PrintShop configured for a "Epson MX-, FX-, RX- (80 or 100)" connected to "Apple II Parallel Interface" in slot 1.
This still does not cleanly pass the bytes to an Epson printer. You'll also want to set `g_bFilterUnprintable` to `false` because that filters out the ESC character that the printer needs, and `g_bPrinterAppend` to `true` because the default setting has a bad habit of resetting the printout.

writes to PIC strobe should not be interpreted as a data byte

---

source/6522.h

and avoid usage of uninitialised values.

SY6522: initialise card.

---

source/Configuration/About.cpp
source/Configuration/PageDisk.cpp
source/Core.cpp
source/Core.h
source/Debugger/Debugger_Help.cpp
source/Disk.cpp
source/DiskImageHelper.cpp
source/FrameBase.cpp
source/FrameBase.h
source/Harddisk.cpp
source/Memory.cpp
source/Registry.cpp
source/Utilities.cpp
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h

There is no need to enter buffer length explicitly for `_sntprintf_s()` which is less error prone.
The calls clearly indicate output string will be truncated (if required) instead of buffer overflow.
The calls are made to be consistently UNICODE capable.

Replace StringCbPrintf() with StrFormat()

---

source/Registry.cpp
source/Registry.h

The static variables are kind of weird that got recomputed upon every call.
The functions can simply return the wanted string as value.

Remove unnecessary static std::string variables

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.cpp
source/Debugger/Debugger_Console.cpp
source/Debugger/Debugger_Console.h
source/Debugger/Debugger_DisassemblerData.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Symbols.cpp
source/Debugger/Debugger_Win32.cpp
source/YamlHelper.h
test/TestDebugger/TestDebugger.cpp
test/TestDebugger/TestDebugger.vcproj

The whole bunch Console print functions in Debugger can now be much simplified with StrFormat().
No longer needs an explicit buffer to help producing the messages.

Simplify console print

---

source/AY8910.cpp
source/Configuration/PageConfig.cpp
source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.cpp
source/Debugger/Debugger_Color.cpp
source/Debugger/Debugger_Disassembler.cpp
source/Debugger/Debugger_Disassembler.h
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Symbols.cpp
source/Debugger/Debugger_Symbols.h
source/DiskFormatTrack.cpp
source/Joystick.cpp
source/SSI263.cpp
source/SerialComms.cpp
source/SerialComms.h
source/Speaker.cpp
source/Windows/AppleWin.cpp
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h
source/Windows/WinFrame.cpp

This PR deals with all the `sprintf_s()` and `wsprintf()` calls and replaces with equivalent `StrFormat()`.
This leads to some possible improvements to SerialComms and `GetSymbol()`/`FormatAddress()` which I separate into individual commits to help review. (I can do if these deserve some separate PRs)
The remaining bigger lot of `sprintf()` will be deal with in another PR.

Replace sprintf_s() and wsprintf() with StrFormat()

---

source/Card.h
source/CardManager.cpp
source/CardManager.h
source/Disk.h
source/FourPlay.h
source/Harddisk.h
source/LanguageCard.h
source/MouseInterface.cpp
source/MouseInterface.h
source/SAM.h
source/SNESMAX.h
source/SerialComms.cpp
source/SerialComms.h
source/Uthernet1.cpp
source/Uthernet1.h
source/Uthernet2.cpp
source/Uthernet2.h
source/Utilities.cpp
source/VidHD.h
source/Windows/WinFrame.cpp

1) Remove Init()
2) Call Reset() via CardManager
3) Destroy() (only used in disks) via CardManager.
The only "real" changes are in CSuperSerialCard: ensure destructor cleans up and remove Destroy().

Card: cleanup interface.

---

source/Debugger/Debug.cpp
source/Debugger/Util_MemoryTextFile.cpp
source/Debugger/Util_MemoryTextFile.h

Just cleaner code using `X.clear()` instead of `X.erase(X.begin(), X.end())`.

Use clear() instread of erase(begin(), end())

---

source/LanguageCard.cpp
source/Memory.cpp
source/SSI263.cpp
source/StrFormat.h

- Simplify common StrFormat(), especially in Debugger (changes upcoming)
- Add helpers StrAppendByteAsHex() and StrAppendWordAsHex()
- Add helpers StrBufferAppendByteAsHex() and StrBufferAppendWordAsHex() for plain string buffer

Add ByteToHexStr() and WordToHexStr()

---

source/Debugger/Debug.cpp

Since both variables are boolean, VC detected and suggested that the intention should be using logical AND `&&` instead of bitwise AND `&`.

Fix to use logical "&&" for boolean variables

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.cpp
source/Debugger/Debugger_Console.cpp
source/Debugger/Debugger_Console.h
source/Debugger/Debugger_DisassemblerData.cpp
source/Debugger/Debugger_Display.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Parser.cpp
source/Debugger/Debugger_Symbols.cpp

Consistently adding space after keywords `if`, `for`, `switch` and `while`.
I have counted, there are more statements having the space than not.
This is only for the Debugger area. Inconsistency still exists in other areas.

Debugger: Format changes only - consistent space after keywords

---

source/Debugger/Debug.cpp

pBmp is never changed and always points to bmp.
I think the code can simple use bmp directly.
Also initialize the bmp structure properly.

Debugger: Remove unnecessary alias pointer

---

source/Debugger/Debugger_Symbols.cpp

- Change `_CmdSymbolsInfoHeader()` to return `std::string`

Debugger: replace sprintf() part 3 - Debugger_Symbols

---

source/Debugger/Debugger_Display.cpp

1. The only call site of DrawFlags() is taking only a BYTE. The function signature should change to prevent upsizing BYTE to WORD and hence the warning.
2. nStackDepth could in theory go over 255, in that case, some special indication should be printed. With the condition checked, casting it to BYTE is now safe.

Fix a couple of warnings from PR#1090

---

source/Debugger/Debugger_DisassemblerData.cpp

- Change `_GetAutoSymbolName()` to return `std::string`

Debugger: replace sprintf() part 5 - Debugger_DisassemblerData

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Disassembler.cpp
source/Debugger/Debugger_Disassembler.h

- Improve `FormatCharCopy()` to not buffer overflow
- Improve `FormatOpcodeBytes()` to not buffer overflow
- Improve `FormatNopcodeBytes()` to not buffer overflow
- Change `FormatDisassemblyLine()` to return `std::string`

Debugger: replace sprintf() part 6 - Debugger_Disassembler

---

source/Debugger/Debug.cpp

- Add `ProfileLine_t` to take care of the profile line buffer
- Simplify `_SearchMemoryDisplay()` without using `StringCat()`
- Simplify `CmdOutputPrint()` significantly

Debugger: replace sprintf() part 7 final - Debug

---

source/Configuration/PageDisk.cpp
source/SaveState.cpp
source/Tfe/IPRaw.cpp
source/Tfe/IPRaw.h
source/Uthernet2.cpp
source/Uthernet2.h
source/W5100.h

Bug fix:
1. UDP: it would not take into account the size of the header (6 bytes) when computing the amount of data that can be read from the peer (so potentially reading 6 bytes too many, which would not fit)
2. IPRAW: The header should contain the `source` of the packet rather than the `destination` (which is useless as it is our IP address). Doc is not very clear, but for UDP (which they refer to) they use the peer IP (so the `source` of the packet), or destination of the socket.
Changes:
1. Make Virtual DNS enabled by default

Uthernet II: 2 fixes and minor changes

---

source/NTSC.cpp

If "GetVideo().GetFrameBufferCentringValue() - kOverscanOffsetL" is negative, it causes an overflow.
There is a dangerous combination of signed, unsigned, 32 and 64 bits and the negative values causes an overflow in 64 bit builds.
https://github.com/audetto/AppleWin/issues/63

Avoid sign extension issues in 64 bit.

---

source/CmdLine.cpp
source/CmdLine.h
source/Disk.cpp
source/Disk.h
source/Disk2CardManager.cpp
source/Disk2CardManager.h
source/Windows/AppleWin.cpp

PR for #1110.
If 2 _adjacent_ stepper control OFF accesses occur within 10 cycles, then update the magnet states, but don't move the cog. So the track/phase doesn't change.
Developer info: all Control Stepper access are now deferred by 10 cycles, which allows detecting of the above condition. The SyncEvent functionality is used to allow this very fine level of detection, without impacting performance - ie. it's the same functionality used for precise interrupts from Mockingboard(6522) & Mouse(VBl) cards.

Two adjacent magnets off in quick succession

---

source/Disk.cpp

error: format not a string literal and no format arguments [-Werror=format-security]

Fix printf warning.

---

source/CardManager.cpp
source/CardManager.h

Corrected the check if multiple Z80 cards are installed. The check was already there, but didn't work - due to incomplete copy&pasting - and a minor goof with the class name...

Properly catch installation of multiple Z80 cards.

---

source/Debugger/Debug.cpp
source/Debugger/Debug.h
source/Debugger/Debugger_Commands.cpp
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Types.h

I would like to propose this PR with a few new features for breakpoints.
First, a little disclosure: I am trying to integrate AppleWin (linux only) into this debugger for CC65 https://github.com/empathicqubit/vscode-cc65-debugger. To achieve this, I need to implement the VICE binary monitor protocol https://vice-emu.sourceforge.io/vice_13.html which requires these (little) extensions to breakpoints.
But, you can simply ignore all the above and look at these features, which I think have a value on their own.
1. add a hit count
2. add a `bStop` flag. if `false` only the hit count is incremented
3. add a `bHit` flag, so it is possible to query which breakpoint(s) have caused the debugger to stop
4. keep temporary breakpoints alive a bit longer, so they can be inspected
In order to ease the …

Breakpoints: some new features

---

docs/Debugger_Changelog.txt
source/Debugger/Debug.cpp
source/Debugger/Debugger_Console.h

Small QoL when a breakpoint is triggered.  See bottom line in debugger.  Color code register and breakpoint number.

Debugger stop reason

---

source/Debugger/Debug.h
source/Debugger/Debugger_Help.cpp

Minor misc. cleanup:
* BP alignment
* remove superfluous tabs
* Fix sections
Normally I would indent `case` in that honking big switch/chase in `CmdHelpSpecific()` but I believe I intentionally coded that inconsistent way to minimize horizontal scrolling decades ago.

Debugger cleanup misc march 2023

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.cpp
source/Debugger/Debugger_Assembler.h

New behavior showing the stack on failure/success. Detect stack state on failure after `JSR` (3 possible states).
1. Failure: RTS address on stack sans extra junk
2. Failure: RTS address on stack with extra junk
3. Failure: RTS address not found on stack (!)
4. Successful step over, like 2, but with increased max execution steps.

Debugger step over

---

docs/Debugger_Changelog.txt
source/Debugger/Debug.cpp

This patch makes the debugger `NTSC LOAD` properly import Windows BMP files exported from GIMP again.   (Found while investigating issue #357 and re-verifying the NTSC palette loading in post 1.26.)
Apparently GIMP changed the way they save BMPs now.
There are multiple version of a Windows BMP file.
Struct Size 
* 0x28 version 3 (and prior?)
* 0x38 version 4 which has Red, Green, and Blue channel masks. (Wish hardware and graphics people would just pick ONE bloody RGBA standard for once but I digress...)
The original `.bmp` files `Default_NTSC_Palette.bmp`, `White_NTSC_Palette.bmp`, `Black_NTSC_Palette.bmp`, `Tweaked_Palette.bmp` on my page http://michael.peopleofhonoronly.com/dev/applewin/ntsc/ have different Red, Green, Blue masks.  Re-exporting them as `.bmp` will cause the debugger to …

Update BMP import from GIMP 2.10 with X8 R8 G8 B8

---

source/Riff.cpp

Previously `g_dwTotalNumberOfBytesWritten` was the number of sample-bytes written, while it was used as total number of bytes written (i.e. the file size).

RIFF: fix sizes.

---

source/Debugger/Debug.cpp
source/Debugger/Debugger_Console.cpp
source/Debugger/Debugger_Console.h
source/Debugger/Debugger_Display.cpp

Included in this PR:
1. Clamp long input line in the debugger
2. Fix backspace showing garbage on the input line when the input line is max characters (78)
3. Add preliminary support for for scrolling a long input line when enabled
4. Colorize the `Illegal Command`
To fully enable a long input line more minor work needs to be done (`ConsoleDisplayPush( ConsoleInputPeek() );` to auto-wrap long lines) but this gets us mostly there.
See #1204 for analysis.

1204 debugger long input crash

---

source/Speaker.cpp

`std::fill_n` works everywhere.

Fix a linux/gcc issue where sizeof(wchar_t)==4.

---

source/MockingboardCardManager.cpp

This change improves
1. save some CPU cycles if no card is present
2. help debugging IDirectSoundBuffer underruns
The are NO underruns, but with this patch, when the read pointer overtakes the write point, it is a real underrun.

Mockingboard: do not play sound unless a card is present.

---

source/FourPlay.cpp
source/Joystick.cpp
source/SNESMAX.cpp

We can't trust JOYSTICKID1 (0) & JOYSTICKID2 (1) indexes with WinMM. ( my 1st device is @ index 4 )
So it's mostly not working & not detecting joysticks.
Detect JOYSTICK_1 & JOYSTICK_2 real indexes instead.

[WinMM] Fix joysticks not detected : first & second devices are not always at index 0 & 1

---

source/Memory.cpp

And add an accessor.
This is not an issue in AW, but it happens if one allows to configure RW size.
The check for NULL is enough to detect exactly which ones were allocated.

Avoid a potential memory leak if RamWorks memory size were configurable.

---

source/AY8910.cpp

Otherwise when it gets here
https://github.com/AppleWin/AppleWin/blob/771282a79265cfc8a5c1c0a91cc9740e10d54e20/source/AY8910.cpp#L526
the first entry is initialised, but 0 and 1 are needed here
https://github.com/AppleWin/AppleWin/blob/771282a79265cfc8a5c1c0a91cc9740e10d54e20/source/AY8910.cpp#L540-L541

Fix read of uninitialised values in sound_ay_overlay().

---

source/Core.cpp
source/Core.h
source/Debugger/Debugger_Symbols.cpp

needed because macOS apps are a bundle (tree of directories) and resources are packaged somewhere within, not necessarily in the same directory as the executable.
probably doesn't deal with the case of user-supplied symbols, but I haven't gotten that far yet...
https://github.com/sh95014/AppleWin/issues/12

Allow alternate directory for built-in symbols

---

docs/Debugger_Changelog.txt
source/Debugger/Debug.cpp
source/Debugger/Debugger_Assembler.h
source/Debugger/Debugger_Disassembler.cpp
source/Debugger/Debugger_DisassemblerData.cpp

@tomcw Some small Quality of Life for the debugger `df` command.
Before:
After:

Debugger df qol

---

docs/Debugger_Changelog.txt
source/Debugger/Debug.cpp
source/Debugger/Debugger_Help.cpp

Fix `R P` oversight not setting status register.
This invalidates PR #1233.

Debugger: 2.9.1.25 Fixed: R P ## wasn't setting P flag status register.

---

source/SoundCore.cpp
source/StdAfx.h

See code comments for more details.

WIN64: Use correct IReferenceClock definition from <strmif.h>

---

source/SSI263.cpp

Fix an assertion that would never trigger.
Avoid assertion (or segfault) when running with `-no-mb`.

Minor bugs in SSI263

---

source/SerialComms.cpp
source/SerialComms.h

Some initial steps to use `SerialComms` in linux.
Current goal is to enable the TCP mode.

Serial comms: compilation in Linux

---

source/6522.cpp
source/Mockingboard.cpp
source/SSI263.cpp
source/SSI263.h

See #175, "Other things":
- A phoneme will continue playing back infinitely; unless the phoneme is changed or CTL=1.
- CTL=1 sets "PD" (Power Down / "standby") mode, also set at power-on.
- CTL=0 brings device out of "PD" mode, the mode will be set to DR1,DR0 and the phoneme P5-P0 will play.
- Setting mode to DR1:0 = %00 just disables A/!R (ie. disables interrupts), but otherwise retains the previous DR1:0 mode.
- RESET is not connected to !PD/!RST pin 18.
- Support edge-case where RESET can enable ints & assert IRQ
- Power-on: PD=1 (so D7=0), reg4 (Filter Freq)=0xFF.
- Support SSI263 IRQ and D7 on a Phasor mode change (including Echo+)
- $Csxx I/O mapping (same for Mockingboard and Phasor mode)
Other:
- SSI263 save-state: simplify load/save SC01
- 6522: Fix reg $F (ORA w/HS) to be …

SSI263 - support for core functionality

---

AppleWin-VS2022.vcxproj
AppleWin-VS2022.vcxproj.filters
source/FrameBase.h
source/MockingboardCardManager.cpp
source/SSI263.cpp
source/SoundBuffer.h
source/SoundCore.cpp
source/SoundCore.h
source/Speaker.cpp
source/Windows/DXSoundBuffer.cpp
source/Windows/DXSoundBuffer.h
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h

Second PR for getting a [libretro core](https://github.com/audetto/AppleWin/issues/44) to compile in the msys2 environment.
This replaces the `LPDIRECTSOUNDBUFFER` pointer with a pure virtual class and an implementation that wraps the `LPDIRECTSOUNDBUFFER`, allowing other sound implementations without having to simulate the exact alignment of a `DIRECTSOUNDBUFFER` object.
Additionally, moves the `DSInit` and `DSUninit` calls out of the SoundCore.cpp file, allowing them to be appropriately reimplemented in a non-DirectSound environment.
Further changes could be made to eliminate the DirectSound-based flag defines, and functions could be renamed to not imply a dependence on DirectSound, but I tried to limit the scope of changes.

add SoundBuffer interface

---

source/FrameBase.h
source/MockingboardCardManager.cpp
source/SSI263.cpp
source/SoundCore.cpp
source/SoundCore.h
source/Speaker.cpp
source/StdAfx.h
source/StrFormat.cpp
source/StrFormat.h
source/Windows/DXSoundBuffer.cpp
source/Windows/DXSoundBuffer.h
source/Windows/Win32Frame.cpp
source/Windows/Win32Frame.h
source/Windows/WinFrame.cpp
source/YamlHelper.cpp
test/TestCPU6502/stdafx.h

1. `SoundBuffer`: move Windows only flags to `DXSoundBuffer`
2. Remove checks for old `_MSC_VER` values

More cleanup

---

AppleWinExpress2019.vcxproj.filters
resource/Applewin.rc
resource/resource.h
source/Debugger/Debugger_Display.cpp

Simplifies linux resource embedding.

DebugFont: use an ID which is a valid macro.

---

source/Windows/WinFrame.cpp

Small typo, you have 2 dots in the extension for the filename when creating new disks.

Double dot in disk filename

---

bin/A2_DOS33.SYM2
docs/Debugger_Changelog.txt
help/CommandLine.html
help/ddi-formats.html
source/Debugger/Debug.cpp
source/Debugger/Debugger_DisassemblerData.cpp
source/Debugger/Debugger_Symbols.cpp
source/DiskImageHelper.cpp

@tomcw I tracked down almost all of the magic numbers for disk sizes in DiskImageHelper.cpp mentioned in #1370.
Do we need update the AppleWin.chm and change this line?
> "Sometimes on the Internet you will see a disk image that is 143,488 or 143,616 bytes long;"
To something more like this?
"Sometimes on the Internet you will see a disk image that is not 143,360 bytes long;"

Document the disk image size magic numbers.

---

source/MockingboardCardManager.cpp
source/SSI263.cpp
source/SaveState.cpp
source/SoundCore.h
source/Speaker.cpp
source/Utilities.cpp

It was set at the maximum level rather than the MockingBoard volume.
At the same time, I have removed some redundant checks.

Fix initial volume of SSI263 and after a Load State.

---

docs/Debugger_Changelog.txt
source/Debugger/Debug.cpp
source/Debugger/Debugger_Commands.cpp
source/Debugger/Debugger_Console.cpp
source/Debugger/Debugger_Console.h
source/Debugger/Debugger_Help.cpp
source/Debugger/Debugger_Symbols.cpp
source/Debugger/Debugger_Symbols.h
source/Debugger/Debugger_Types.h

See #1420 and #1421 for details.
@tomcw I'm very happy with this functionality. I can control the amount of debugger startup spam `LOG *` , view the current level, and easily reload the debugger symbol files `STARTUP`.
I think we're good to merge?

Debugger output error levels
