AppleWin/AppleWin

- source/Video.cpp
> Delete unused code from Video.cpp

- resource/Applewin.rc
- source/Mockingboard.cpp
- source/Mockingboard.h
> Support Mockingboard when polling IFR.Timer1

- docs/Debugger_Changelog.txt
- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Display.cpp
- source/Debugger/Debugger_Symbols.cpp
> Bug 479 fixes

- HookFilter/HookFilter.cpp
- source/Debugger/Debug.cpp
- source/Frame.cpp
- source/Keyboard.cpp
- source/Keyboard.h
Better support for AltGr as ClosedApple key.
> GH558 ClosedApple

- source/Applewin.cpp
- source/Disk.cpp
> DiskII: Support partial nibble reads for very close disk latch reads

- source/Applewin.cpp
- source/Configuration/PageDisk.cpp
- source/Configuration/PropertySheetHelper.cpp
- source/Debugger/Debug.cpp
- source/Disk.cpp
- source/Disk.h
- source/DiskFormatTrack.cpp
- source/DiskFormatTrack.h
- source/DiskImage.cpp
- source/DiskImage.h
- source/DiskImageHelper.cpp
- source/DiskImageHelper.h
- source/Frame.cpp
- source/Harddisk.cpp
- source/Memory.cpp
- source/SaveState.cpp
- source/Video.cpp
Refactored Disk.cpp into a class.
> Refactor Disk.cpp

- source/Debugger/Debug.cpp
- source/Debugger/Debug.h
- source/Debugger/DebugDefs.h
- source/Debugger/Debugger_Assembler.cpp
- source/Debugger/Debugger_Commands.cpp
- source/Debugger/Debugger_Display.cpp
- source/Debugger/Debugger_Help.cpp
- source/Debugger/Debugger_Types.h
Extended BPM to also support BPMR and BPMW
Fixed BPM[R|W] 0:FFFF (ie. support a range of 0x10000)
> Debugger: BPMR & BPMW

- source/SerialComms.cpp
- source/SerialComms.h
> ADTPro not working

- source/CPU.cpp
- source/Mockingboard.cpp
- source/Mockingboard.h
- source/Video.cpp
> Fix for "Mad Effect 1&2" demos

- source/RGBMonitor.cpp
Without vertical blend: 18.8 MHz -> 29.7 MHz
With vertical blend: 14.2 MHz -> 15.0 MHz
> RGB Monitor: speed up video update.

- source/Harddisk.cpp
> Correct way to clear a std::string.

- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Commands.cpp
- source/Debugger/Debugger_Display.cpp
- source/Debugger/Debugger_Display.h
- source/Debugger/Debugger_Help.cpp
- source/Debugger/Debugger_Types.h
> Debugger: Extend 'cycles' command to do (partial) timings

- source/Debugger/Debug.cpp
PR for #783.
Add cycles for trace
Also don't call DrawFlags(), speeding up tracing by 10 times.
> Debugger: add cycles for tf

- source/AY8910.cpp
- source/AY8910.h
- source/Mockingboard.cpp
- source/SoundCore.cpp
- source/SoundCore.h
Add const, static forward declaration.
Remove windows.h (already in StdAfx.h) and crtdbg.h (not needed).
> Some minor c++ correctness changes.

- source/Applewin.cpp
- source/Mockingboard.cpp
- source/Riff.cpp
- source/Riff.h
- source/Speaker.cpp
Make code compile when enabling RIFF_XXX.
Add const to Riff arguments.
Format of perf breakdown.
> Minor fixes

- README.md
Updated download links to new and previous versions.
AppleWin v1.29.13.0
> Bumping version in README (AppleWin v1.29.13.0)

- source/CPU.cpp
- source/CPU/cpu_general.inl
- source/CPU/cpu_heatmap.inl
- source/Memory.cpp
- source/Memory.h
- source/NoSlotClock.cpp
- source/NoSlotClock.h
- test/TestCPU6502/TestCPU6502.cpp
> Support NSC for Apple II/II+ via F8-ROM

- source/Interface.h
- source/Utilities.cpp
- source/Utilities.h
- source/Windows/WinFrame.cpp
Code is generic and can be moved out of WinFrame.cpp.
> Reset: move CtrlReset() and ResetMachineState() to Utilities.cpp

- source/CardManager.cpp
- source/CardManager.h
And remove one-off NULL check (slots are never NULL).
> Fix memory leak in CardManager

- source/DiskImageHelper.cpp
- source/Harddisk.cpp
- source/Memory.cpp
- source/Windows/WinVideo.cpp
CopyMemory, MoveMemory, FillMemory.
> Remove a few more Win32 memory functions.

- source/Disk.cpp
- source/Disk.h
> Improved support for latch when drive is empty

- docs/CodingConventions.txt
> Coding Conventions updated

- source/CPU.cpp
- source/CmdLine.cpp
- source/CmdLine.h
- source/Configuration/Config.h
- source/Configuration/PageAdvanced.cpp
- source/Configuration/PageConfig.cpp
- source/Configuration/PageDisk.cpp
- source/Configuration/PageInput.cpp
- source/Configuration/PageSound.cpp
- source/Configuration/PropertySheetHelper.cpp
- source/Core.cpp
- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Display.cpp
- source/Disk.cpp
- source/Harddisk.cpp
- source/Interface.h
- source/Memory.cpp
- source/MouseInterface.cpp
- source/NTSC.cpp
- source/NTSC.h
- source/NTSC_CharSet.cpp
- source/RGBMonitor.cpp
- source/SaveState.cpp
- source/Utilities.cpp
- source/Video.cpp
- source/Video.h
- source/Windows/AppleWin.cpp
- source/Windows/WinFrame.cpp
- source/Windows/WinVideo.cpp
- source/Windows/WinVideo.h
Currently the singleton returned by GetVideo() is just a class Video instance.
I still plan to derive WinVideo from Video, and return the WinVideo subclass instead.
> Make Video.cpp into a class, with a GetVideo() singleton in AppleWin.cpp

- source/Configuration/PageConfig.cpp
- source/Debugger/Debug.cpp
- source/FrameBase.cpp
- source/FrameBase.h
- source/Keyboard.cpp
- source/Speaker.cpp
- source/Video.cpp
- source/Video.h
- source/Windows/WinFrame.cpp
- source/Windows/WinVideo.cpp
It avoids some hoops between GetVideo and GetFrame.
> Move VideoRedrawScreen() to Video.

- HookFilter/HookFilter.cpp
- source/Configuration/About.cpp
- source/Configuration/IPropertySheetPage.h
- source/Configuration/PageAdvanced.cpp
- source/Configuration/PageAdvanced.h
- source/Configuration/PageConfig.cpp
- source/Configuration/PageConfig.h
- source/Configuration/PageConfigTfe.cpp
- source/Configuration/PageConfigTfe.h
- source/Configuration/PageDisk.cpp
- source/Configuration/PageDisk.h
- source/Configuration/PageInput.cpp
- source/Configuration/PageInput.h
- source/Configuration/PageSound.cpp
- source/Configuration/PageSound.h
- source/Configuration/PropertySheet.cpp
- source/Tfe/Tfe.cpp
Here are a few changes to make 64-bit build possible.
The changes are mainly to use windows api in the correct way that works for both 32-bit and 64-bit builds.
> X64 enabling

- help/cfg-advanced.html
- source/Common.h
- source/Core.cpp
- source/Core.h
- source/Keyboard.cpp
- source/Keyboard.h
- source/Memory.cpp
- source/ParallelPrinter.cpp
- source/Pravets.cpp
- source/Pravets.h
- source/SaveState.cpp
- source/Tape.cpp
- source/Tape.h
- source/Utilities.cpp
- source/Windows/WinFrame.cpp
. add new Pravets class
. move all the Pravets special code into the new class
> Pravets refactor

- AppleWinExpress2008.vcproj
- AppleWinExpress2019.vcxproj
- AppleWinExpress2019.vcxproj.filters
- source/Debugger/Debug.cpp
- source/Debugger/Debug.h
- source/Debugger/Debugger_Color.cpp
- source/Debugger/Debugger_Display.h
- source/Debugger/Debugger_Help.cpp
- source/Debugger/Debugger_Win32.cpp
- source/Debugger/Debugger_Win32.h
- source/Windows/AppleWin.cpp
And replace _tcscat -> strcat to maximise portability.
> Debugger: move Win32 functions to separate file.

- source/CmdLine.h
- source/Disk.cpp
- source/Harddisk.cpp
- source/Harddisk.h
- source/Utilities.cpp
- source/Utilities.h
A few small changes to improve string handling.
> Move some "char *" -> "const char *", and avoid non necessary c_str().

- source/Configuration/PropertySheetHelper.cpp
- source/Memory.cpp
- source/SaveState.cpp
- source/Tfe/tfe.cpp
- source/Tfe/tfe.h
- source/Utilities.cpp
- source/Windows/AppleWin.cpp
> Support Uthernet save-state

- source/Card.cpp
- source/Card.h
- source/CardManager.cpp
- source/CardManager.h
- source/Disk.cpp
- source/Disk.h
- source/FourPlay.cpp
- source/FourPlay.h
- source/Harddisk.cpp
- source/Harddisk.h
- source/LanguageCard.cpp
- source/LanguageCard.h
- source/MouseInterface.cpp
- source/MouseInterface.h
- source/ParallelPrinter.cpp
- source/ParallelPrinter.h
- source/SAM.cpp
- source/SAM.h
- source/SNESMAX.cpp
- source/SNESMAX.h
- source/SaveState.cpp
- source/SerialComms.cpp
- source/SerialComms.h
- source/Tfe/tfe.cpp
- source/Tfe/tfe.h
Add 2 virtual methods to `Card` to load and save snapshots.
> Card::Save/LoadSnapshot

- source/VidHD.cpp
- source/Video.cpp
This is already done for the other video modes:
https://github.com/AppleWin/AppleWin/blob/0ac210b13285e8434b908202171e2852cd068516/source/Video.h#L3-L11
> Set SHR Alpha to 255 for maximum compatibility.

- source/AY8910.cpp
- source/CPU.cpp
- source/Disk.cpp
- source/DiskFormatTrack.cpp
- source/FourPlay.cpp
- source/Harddisk.cpp
- source/LanguageCard.cpp
- source/Memory.cpp
- source/Mockingboard.cpp
- source/MouseInterface.cpp
- source/ParallelPrinter.cpp
- source/RGBMonitor.cpp
- source/SAM.cpp
- source/SNESMAX.cpp
- source/SSI263.cpp
- source/SaveState.cpp
- source/SerialComms.cpp
- source/Tfe/tfe.cpp
- source/VidHD.cpp
- source/Windows/AppleWin.cpp
- source/YamlHelper.cpp
- source/YamlHelper.h
- source/Z80VICE/z80.cpp
Change all `throw std::string` to `std::runtime_error`.
And add some extra info to `yaml` errors.
> throw std::runtime_error

- source/Card.cpp
- source/Card.h
- source/Configuration/PropertySheetHelper.cpp
- source/Configuration/PropertySheetHelper.h
- source/Disk.cpp
- source/FourPlay.cpp
- source/Harddisk.cpp
- source/LanguageCard.cpp
- source/Mockingboard.cpp
- source/MouseInterface.cpp
- source/ParallelPrinter.cpp
- source/SAM.cpp
- source/SNESMAX.cpp
- source/SaveState.cpp
- source/SerialComms.cpp
- source/Tfe/tfe.cpp
- source/VidHD.cpp
- source/Z80VICE/z80.cpp
For invalid slot and invalid version.
> Cards: improve error messages.

- source/CmdLine.cpp
- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Console.h
- source/Debugger/Debugger_Help.cpp
- source/YamlHelper.h
> Fix some format errors.

- source/Disk.cpp
- source/Disk.h
- source/LanguageCard.cpp
- source/Memory.cpp
- source/SSI263.cpp
- source/StrFormat.h
- source/Tfe/tfearch.cpp
- source/Uthernet1.cpp
After this, the remaining sprintf() usages *should* all be within the debugger area.
> Replace sprintf() with StrFormat()

- source/SaveState.cpp
- source/Uthernet2.cpp
- source/Uthernet2.h
- source/W5100.h
This seems to work, but I need some more testing.
> Uthernet II: implement save state.

- source/CardManager.cpp
- source/Configuration/PropertySheetHelper.cpp
- source/Disk.cpp
- source/Harddisk.cpp
> Cards: remove special call to InitializeIO for Disk and HardDisk.

- source/Debugger/Debug.cpp
- source/Debugger/Util_MemoryTextFile.cpp
- source/Debugger/Util_MemoryTextFile.h
- Add MemoryTextFile_t::PushLineFormat()
- Replace some sprintf() with PushLineFormat()
> Debugger: replace sprintf() part 1

- source/Configuration/PageConfigTfe.cpp
- source/Configuration/PageConfigTfe.h
- source/Tfe/PCapBackend.cpp
- source/Tfe/PCapBackend.h
- source/Tfe/tfearch.cpp
- source/Tfe/tfearch.h
- source/Tfe/tfesupp.cpp
- source/Tfe/tfesupp.h
> tfesupp: remove all manual string manipulations.

- AppleWinExpress2019.vcxproj
- AppleWinExpress2019.vcxproj.filters
- source/Tfe/IPRaw.cpp
- source/Tfe/IPRaw.h
- source/Tfe/NetworkBackend.h
- source/Tfe/PCapBackend.cpp
- source/Tfe/PCapBackend.h
- source/Uthernet2.cpp
- source/Uthernet2.h
- source/W5100.h
I think the emulation for IPRAW sockets is complete (except potentially some errata).
Missing are some more extensive test cases, the only existing one is A2OSX.
But even this will make it easier to test it and validate further.
> Uthernet II: implement IPRAW sockets.

- help/toc.html
- help/uthernet.html
- source/Uthernet2.cpp
- source/Uthernet2.h
> Uthernet II: handle TCP connection failure.

- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Disassembler.cpp
- source/Debugger/Debugger_DisassemblerData.cpp
- source/Debugger/Debugger_Display.cpp
- Fix some inconsistent indentations
- Add some curly brackets to clarify structure
> Debugger: Format changes only

- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Disassembler.cpp
- source/Debugger/Debugger_Display.cpp
- source/Debugger/Debugger_Symbols.cpp
While the memory is still fresh, let me clean up the wrong prefix I put in through some earlier PRs.
> Debugger: replace prefix 'str' with 's'

- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Display.cpp
- source/Debugger/Debugger_Symbols.cpp
- Move loop variable definitions into for-statement (minimise scope)
- Move some variables used only in loops inside the loops (minimise scope)
- Move a few variables closer to where they are used (reduce scope)
> Debugger: Improve some for-loops definitions

- source/Debugger/Debug.cpp
- source/Debugger/Debug.h
- source/Harddisk.cpp
> Debugger memory breakpoint support for HDD DMA r/w

- source/Debugger/Debug.cpp
> Fix static declaration.

- source/Debugger/Debugger_Help.cpp
- source/Debugger/Debugger_Help.h
> Replace/remove StringCat() and friends

- source/CmdLine.cpp
- source/SNESMAX.cpp
- source/SNESMAX.h
- source/SaveState.cpp
- source/YamlHelper.cpp
- source/YamlHelper.h
> Support controller-button remapping file for SNES MAX

- docs/Debugger_Changelog.txt
- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Assembler.cpp
> Debugger 2.9.1.14 Fix disassembly when in middle of data

- source/CmdLine.cpp
- source/Debugger/Debugger_Disassembler.cpp
I have forgotten them in the recent PRs.
> 2 small fixes: enum comparison and include.

- source/6522.cpp
- source/6522.h
- source/Card.cpp
- source/Card.h
- source/CardManager.cpp
- source/CmdLine.cpp
- source/Configuration/PageSound.cpp
- source/Configuration/PageSound.h
- source/Mockingboard.cpp
- source/Mockingboard.h
- source/MockingboardCardManager.cpp
- source/Windows/AppleWin.cpp
Added to test mb-audit's support for this card.
> Add MegaAudio card

- docs/Debugger_Changelog.txt
- source/Debugger/Debug.cpp
- source/Debugger/Debugger_Color.cpp
- source/Debugger/Debugger_Display.cpp
Fixed edge case having wrong colors when in BW mode.
> 1231 disassembly of current line is illegible in black white mode

- source/Joystick.cpp
> Support 'squaring the circle' for analog sticks

- help/cfg-advanced.html
- source/Configuration/PageAdvanced.cpp
- source/CopyProtectionDongles.cpp
- source/CopyProtectionDongles.h
- source/Joystick.cpp
> Support Robocom's Interface Module protection dongle

- source/Uthernet2.cpp
This PR changes the way a socket is marked as "non-blocking" in linux.
The call to `fcntl` is more portable and available in macOS too.
Linux offers an easier alternative (an argument to `socket`), which does not exist in macOS.
The final result is the same, with no special `#ifdef` required for macOS (which at the moment does not work).
At the same time, an error is reported on all platform if the "non-blocking" flag fails.
> Uthernet2: use fcntl for better compatibility with MacOS.

- help/CommandLine.html
- help/dbg-screen-layout.html
- help/savestate.html
- source/CardManager.cpp
- source/CardManager.h
- source/CmdLine.cpp
- source/Debugger/Debugger_Display.cpp
- source/LanguageCard.cpp
- source/LanguageCard.h
- source/Memory.cpp
- source/Memory.h
- source/SaveState.cpp
- source/Utilities.cpp
- source/Windows/AppleWin.cpp
NB. Command line config only, and only permitted in slot 3 for now.
For #1279.
> Support an extra Saturn card in slot 3 and for all Apple II models.

- source/Memory.cpp
> Fix for GH1285: 2x adjacent 64K pages mapped to same physical page

- source/Uthernet1.cpp
- source/Uthernet2.cpp
> Uthernet (II) I/O support

- source/Configuration/PageAdvanced.cpp
- source/CopyProtectionDongles.cpp
- source/CopyProtectionDongles.h
- source/SaveState.cpp
> Support Hayden dongle

- source/Debugger/Debug.cpp
- source/Memory.cpp
- source/Memory.h
- source/VidHD.cpp
> Gh1267 update paging

- help/savestate.html
- source/Disk.cpp
- source/Harddisk.cpp
https://github.com/AppleWin/AppleWin/issues/1290
> SaveState: add absolute path for disks.

- source/6522.cpp
- source/6522.h
> Fix edge-case for 6522 Timer write

- source/Harddisk.cpp
- source/Harddisk.h
> Fix SmartPort Status cmd when reading status to aux mem

- help/CommandLine.html
- source/CardManager.cpp
- source/CardManager.h
- source/CmdLine.cpp
- source/Common.h
- source/Memory.cpp
- source/Memory.h
- source/Utilities.cpp
- source/Windows/AppleWin.cpp
> RamWorks III - 16MB support

- source/Mockingboard.cpp
- source/MockingboardCardManager.cpp
- source/SSI263.cpp
- source/SSI263.h
> Restore SSI263 phoneme playback from save-state

- source/Mockingboard.cpp
- source/SSI263.cpp
- source/SSI263.h
> Restore SC01 phoneme playback from save-state

- docs/Debugger_Changelog.txt
- help/dbg-toc-intro.html
- help/dbg-view-output.html
- source/Debugger/Debug.cpp
@tomcw  This should be ready to be merged.
> #1384 Debugger view output QoL

- README.md
@tomcw Minor PR to update the main `README.md`
* Add links to unofficial ports, and
* Add models supported and not supported.
> Update readme with forks and models
